// Defines the message contract for the Data Sources service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/lib/types/v1/data-source.proto

package datasources_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreCollectionsPb struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BundleCollection     string                 `protobuf:"bytes,1,opt,name=bundle_collection,json=bundleCollection,proto3" json:"bundle_collection,omitempty"`
	FilesCollection      string                 `protobuf:"bytes,2,opt,name=files_collection,json=filesCollection,proto3" json:"files_collection,omitempty"`
	ProfilesCollection   string                 `protobuf:"bytes,3,opt,name=profiles_collection,json=profilesCollection,proto3" json:"profiles_collection,omitempty"`
	DatagroupsCollection string                 `protobuf:"bytes,4,opt,name=datagroups_collection,json=datagroupsCollection,proto3" json:"datagroups_collection,omitempty"` // NEW: Added collection for groups
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StoreCollectionsPb) Reset() {
	*x = StoreCollectionsPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCollectionsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCollectionsPb) ProtoMessage() {}

func (x *StoreCollectionsPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCollectionsPb.ProtoReflect.Descriptor instead.
func (*StoreCollectionsPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{0}
}

func (x *StoreCollectionsPb) GetBundleCollection() string {
	if x != nil {
		return x.BundleCollection
	}
	return ""
}

func (x *StoreCollectionsPb) GetFilesCollection() string {
	if x != nil {
		return x.FilesCollection
	}
	return ""
}

func (x *StoreCollectionsPb) GetProfilesCollection() string {
	if x != nil {
		return x.ProfilesCollection
	}
	return ""
}

func (x *StoreCollectionsPb) GetDatagroupsCollection() string {
	if x != nil {
		return x.DatagroupsCollection
	}
	return ""
}

type FilterRulesPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRulesPb) Reset() {
	*x = FilterRulesPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRulesPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRulesPb) ProtoMessage() {}

func (x *FilterRulesPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRulesPb.ProtoReflect.Descriptor instead.
func (*FilterRulesPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{1}
}

func (x *FilterRulesPb) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *FilterRulesPb) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type ProfilePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RulesYaml     string                 `protobuf:"bytes,3,opt,name=rules_yaml,json=rulesYaml,proto3" json:"rules_yaml,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilePb) Reset() {
	*x = ProfilePb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePb) ProtoMessage() {}

func (x *ProfilePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePb.ProtoReflect.Descriptor instead.
func (*ProfilePb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{2}
}

func (x *ProfilePb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfilePb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfilePb) GetRulesYaml() string {
	if x != nil {
		return x.RulesYaml
	}
	return ""
}

func (x *ProfilePb) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProfilePb) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DataSourceAnalysisPb struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalFiles     int32                  `protobuf:"varint,1,opt,name=total_files,json=totalFiles,proto3" json:"total_files,omitempty"`
	TotalSizeBytes int32                  `protobuf:"varint,2,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	Extensions     map[string]int32       `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataSourceAnalysisPb) Reset() {
	*x = DataSourceAnalysisPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceAnalysisPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceAnalysisPb) ProtoMessage() {}

func (x *DataSourceAnalysisPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceAnalysisPb.ProtoReflect.Descriptor instead.
func (*DataSourceAnalysisPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{3}
}

func (x *DataSourceAnalysisPb) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *DataSourceAnalysisPb) GetTotalSizeBytes() int32 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *DataSourceAnalysisPb) GetExtensions() map[string]int32 {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type DataSourceMetadataPb struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Repo            string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch          string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	SyncedCommitSha string                 `protobuf:"bytes,4,opt,name=synced_commit_sha,json=syncedCommitSha,proto3" json:"synced_commit_sha,omitempty"`
	LastSyncedAt    int64                  `protobuf:"varint,5,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"`
	FileCount       int32                  `protobuf:"varint,6,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Analysis        *DataSourceAnalysisPb  `protobuf:"bytes,8,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataSourceMetadataPb) Reset() {
	*x = DataSourceMetadataPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSourceMetadataPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSourceMetadataPb) ProtoMessage() {}

func (x *DataSourceMetadataPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSourceMetadataPb.ProtoReflect.Descriptor instead.
func (*DataSourceMetadataPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{4}
}

func (x *DataSourceMetadataPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSourceMetadataPb) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DataSourceMetadataPb) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *DataSourceMetadataPb) GetSyncedCommitSha() string {
	if x != nil {
		return x.SyncedCommitSha
	}
	return ""
}

func (x *DataSourceMetadataPb) GetLastSyncedAt() int64 {
	if x != nil {
		return x.LastSyncedAt
	}
	return 0
}

func (x *DataSourceMetadataPb) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *DataSourceMetadataPb) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataSourceMetadataPb) GetAnalysis() *DataSourceAnalysisPb {
	if x != nil {
		return x.Analysis
	}
	return nil
}

type FileMetadataPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Extension     string                 `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadataPb) Reset() {
	*x = FileMetadataPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadataPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataPb) ProtoMessage() {}

func (x *FileMetadataPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataPb.ProtoReflect.Descriptor instead.
func (*FileMetadataPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{5}
}

func (x *FileMetadataPb) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadataPb) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadataPb) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type DataGroupSourcePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataSourceId  string                 `protobuf:"bytes,1,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	ProfileId     *string                `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataGroupSourcePb) Reset() {
	*x = DataGroupSourcePb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataGroupSourcePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataGroupSourcePb) ProtoMessage() {}

func (x *DataGroupSourcePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataGroupSourcePb.ProtoReflect.Descriptor instead.
func (*DataGroupSourcePb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{6}
}

func (x *DataGroupSourcePb) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

func (x *DataGroupSourcePb) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type DataGroupPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Sources       []*DataGroupSourcePb   `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., for Gemini compiledCacheId and expiry
	CreatedAt     *string                `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataGroupPb) Reset() {
	*x = DataGroupPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataGroupPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataGroupPb) ProtoMessage() {}

func (x *DataGroupPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataGroupPb.ProtoReflect.Descriptor instead.
func (*DataGroupPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{7}
}

func (x *DataGroupPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataGroupPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataGroupPb) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DataGroupPb) GetSources() []*DataGroupSourcePb {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *DataGroupPb) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataGroupPb) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *DataGroupPb) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type CreateDataSourceRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataSourceRequestPb) Reset() {
	*x = CreateDataSourceRequestPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataSourceRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataSourceRequestPb) ProtoMessage() {}

func (x *CreateDataSourceRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataSourceRequestPb.ProtoReflect.Descriptor instead.
func (*CreateDataSourceRequestPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDataSourceRequestPb) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CreateDataSourceRequestPb) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type SyncRequestPb struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IngestionRules *FilterRulesPb         `protobuf:"bytes,1,opt,name=ingestion_rules,json=ingestionRules,proto3" json:"ingestion_rules,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequestPb) Reset() {
	*x = SyncRequestPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequestPb) ProtoMessage() {}

func (x *SyncRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequestPb.ProtoReflect.Descriptor instead.
func (*SyncRequestPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRequestPb) GetIngestionRules() *FilterRulesPb {
	if x != nil {
		return x.IngestionRules
	}
	return nil
}

type SyncResponsePb struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CacheId        string                 `protobuf:"bytes,1,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FilesProcessed int32                  `protobuf:"varint,3,opt,name=files_processed,json=filesProcessed,proto3" json:"files_processed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncResponsePb) Reset() {
	*x = SyncResponsePb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponsePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponsePb) ProtoMessage() {}

func (x *SyncResponsePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponsePb.ProtoReflect.Descriptor instead.
func (*SyncResponsePb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{10}
}

func (x *SyncResponsePb) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *SyncResponsePb) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncResponsePb) GetFilesProcessed() int32 {
	if x != nil {
		return x.FilesProcessed
	}
	return 0
}

type ProfileRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RulesYaml     string                 `protobuf:"bytes,2,opt,name=rules_yaml,json=rulesYaml,proto3" json:"rules_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequestPb) Reset() {
	*x = ProfileRequestPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequestPb) ProtoMessage() {}

func (x *ProfileRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequestPb.ProtoReflect.Descriptor instead.
func (*ProfileRequestPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{11}
}

func (x *ProfileRequestPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileRequestPb) GetRulesYaml() string {
	if x != nil {
		return x.RulesYaml
	}
	return ""
}

type DataGroupRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Sources       []*DataGroupSourcePb   `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataGroupRequestPb) Reset() {
	*x = DataGroupRequestPb{}
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataGroupRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataGroupRequestPb) ProtoMessage() {}

func (x *DataGroupRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_lib_types_v1_data_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataGroupRequestPb.ProtoReflect.Descriptor instead.
func (*DataGroupRequestPb) Descriptor() ([]byte, []int) {
	return file_src_lib_types_v1_data_source_proto_rawDescGZIP(), []int{12}
}

func (x *DataGroupRequestPb) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataGroupRequestPb) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *DataGroupRequestPb) GetSources() []*DataGroupSourcePb {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *DataGroupRequestPb) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_src_lib_types_v1_data_source_proto protoreflect.FileDescriptor

const file_src_lib_types_v1_data_source_proto_rawDesc = "" +
	"\n" +
	"\"src/lib/types/v1/data-source.proto\x12\x18src.types.datasources.v1\"\xd2\x01\n" +
	"\x12StoreCollectionsPb\x12+\n" +
	"\x11bundle_collection\x18\x01 \x01(\tR\x10bundleCollection\x12)\n" +
	"\x10files_collection\x18\x02 \x01(\tR\x0ffilesCollection\x12/\n" +
	"\x13profiles_collection\x18\x03 \x01(\tR\x12profilesCollection\x123\n" +
	"\x15datagroups_collection\x18\x04 \x01(\tR\x14datagroupsCollection\"C\n" +
	"\rFilterRulesPb\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"\x8c\x01\n" +
	"\tProfilePb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"rules_yaml\x18\x03 \x01(\tR\trulesYaml\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\x80\x02\n" +
	"\x14DataSourceAnalysisPb\x12\x1f\n" +
	"\vtotal_files\x18\x01 \x01(\x05R\n" +
	"totalFiles\x12(\n" +
	"\x10total_size_bytes\x18\x02 \x01(\x05R\x0etotalSizeBytes\x12^\n" +
	"\n" +
	"extensions\x18\x03 \x03(\v2>.src.types.datasources.v1.DataSourceAnalysisPb.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa7\x02\n" +
	"\x14DataSourceMetadataPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12*\n" +
	"\x11synced_commit_sha\x18\x04 \x01(\tR\x0fsyncedCommitSha\x12$\n" +
	"\x0elast_synced_at\x18\x05 \x01(\x03R\flastSyncedAt\x12\x1d\n" +
	"\n" +
	"file_count\x18\x06 \x01(\x05R\tfileCount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12J\n" +
	"\banalysis\x18\b \x01(\v2..src.types.datasources.v1.DataSourceAnalysisPbR\banalysis\"a\n" +
	"\x0eFileMetadataPb\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x05R\tsizeBytes\x12\x1c\n" +
	"\textension\x18\x03 \x01(\tR\textension\"l\n" +
	"\x11DataGroupSourcePb\x12$\n" +
	"\x0edata_source_id\x18\x01 \x01(\tR\fdataSourceId\x12\"\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tH\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"\xa3\x03\n" +
	"\vDataGroupPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12E\n" +
	"\asources\x18\x04 \x03(\v2+.src.types.datasources.v1.DataGroupSourcePbR\asources\x12O\n" +
	"\bmetadata\x18\x05 \x03(\v23.src.types.datasources.v1.DataGroupPb.MetadataEntryR\bmetadata\x12\"\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tH\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\a \x01(\tH\x02R\tupdatedAt\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"G\n" +
	"\x19CreateDataSourceRequestPb\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"a\n" +
	"\rSyncRequestPb\x12P\n" +
	"\x0fingestion_rules\x18\x01 \x01(\v2'.src.types.datasources.v1.FilterRulesPbR\x0eingestionRules\"l\n" +
	"\x0eSyncResponsePb\x12\x19\n" +
	"\bcache_id\x18\x01 \x01(\tR\acacheId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0ffiles_processed\x18\x03 \x01(\x05R\x0efilesProcessed\"E\n" +
	"\x10ProfileRequestPb\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"rules_yaml\x18\x02 \x01(\tR\trulesYaml\"\xbb\x02\n" +
	"\x12DataGroupRequestPb\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12E\n" +
	"\asources\x18\x03 \x03(\v2+.src.types.datasources.v1.DataGroupSourcePbR\asources\x12V\n" +
	"\bmetadata\x18\x04 \x03(\v2:.src.types.datasources.v1.DataGroupRequestPb.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_descriptionBGZEgithub.com/tinywideclouds/gen-data-sources/go/types/v1;datasources_v1b\x06proto3"

var (
	file_src_lib_types_v1_data_source_proto_rawDescOnce sync.Once
	file_src_lib_types_v1_data_source_proto_rawDescData []byte
)

func file_src_lib_types_v1_data_source_proto_rawDescGZIP() []byte {
	file_src_lib_types_v1_data_source_proto_rawDescOnce.Do(func() {
		file_src_lib_types_v1_data_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_lib_types_v1_data_source_proto_rawDesc), len(file_src_lib_types_v1_data_source_proto_rawDesc)))
	})
	return file_src_lib_types_v1_data_source_proto_rawDescData
}

var file_src_lib_types_v1_data_source_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_src_lib_types_v1_data_source_proto_goTypes = []any{
	(*StoreCollectionsPb)(nil),        // 0: src.types.datasources.v1.StoreCollectionsPb
	(*FilterRulesPb)(nil),             // 1: src.types.datasources.v1.FilterRulesPb
	(*ProfilePb)(nil),                 // 2: src.types.datasources.v1.ProfilePb
	(*DataSourceAnalysisPb)(nil),      // 3: src.types.datasources.v1.DataSourceAnalysisPb
	(*DataSourceMetadataPb)(nil),      // 4: src.types.datasources.v1.DataSourceMetadataPb
	(*FileMetadataPb)(nil),            // 5: src.types.datasources.v1.FileMetadataPb
	(*DataGroupSourcePb)(nil),         // 6: src.types.datasources.v1.DataGroupSourcePb
	(*DataGroupPb)(nil),               // 7: src.types.datasources.v1.DataGroupPb
	(*CreateDataSourceRequestPb)(nil), // 8: src.types.datasources.v1.CreateDataSourceRequestPb
	(*SyncRequestPb)(nil),             // 9: src.types.datasources.v1.SyncRequestPb
	(*SyncResponsePb)(nil),            // 10: src.types.datasources.v1.SyncResponsePb
	(*ProfileRequestPb)(nil),          // 11: src.types.datasources.v1.ProfileRequestPb
	(*DataGroupRequestPb)(nil),        // 12: src.types.datasources.v1.DataGroupRequestPb
	nil,                               // 13: src.types.datasources.v1.DataSourceAnalysisPb.ExtensionsEntry
	nil,                               // 14: src.types.datasources.v1.DataGroupPb.MetadataEntry
	nil,                               // 15: src.types.datasources.v1.DataGroupRequestPb.MetadataEntry
}
var file_src_lib_types_v1_data_source_proto_depIdxs = []int32{
	13, // 0: src.types.datasources.v1.DataSourceAnalysisPb.extensions:type_name -> src.types.datasources.v1.DataSourceAnalysisPb.ExtensionsEntry
	3,  // 1: src.types.datasources.v1.DataSourceMetadataPb.analysis:type_name -> src.types.datasources.v1.DataSourceAnalysisPb
	6,  // 2: src.types.datasources.v1.DataGroupPb.sources:type_name -> src.types.datasources.v1.DataGroupSourcePb
	14, // 3: src.types.datasources.v1.DataGroupPb.metadata:type_name -> src.types.datasources.v1.DataGroupPb.MetadataEntry
	1,  // 4: src.types.datasources.v1.SyncRequestPb.ingestion_rules:type_name -> src.types.datasources.v1.FilterRulesPb
	6,  // 5: src.types.datasources.v1.DataGroupRequestPb.sources:type_name -> src.types.datasources.v1.DataGroupSourcePb
	15, // 6: src.types.datasources.v1.DataGroupRequestPb.metadata:type_name -> src.types.datasources.v1.DataGroupRequestPb.MetadataEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_src_lib_types_v1_data_source_proto_init() }
func file_src_lib_types_v1_data_source_proto_init() {
	if File_src_lib_types_v1_data_source_proto != nil {
		return
	}
	file_src_lib_types_v1_data_source_proto_msgTypes[6].OneofWrappers = []any{}
	file_src_lib_types_v1_data_source_proto_msgTypes[7].OneofWrappers = []any{}
	file_src_lib_types_v1_data_source_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_lib_types_v1_data_source_proto_rawDesc), len(file_src_lib_types_v1_data_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_lib_types_v1_data_source_proto_goTypes,
		DependencyIndexes: file_src_lib_types_v1_data_source_proto_depIdxs,
		MessageInfos:      file_src_lib_types_v1_data_source_proto_msgTypes,
	}.Build()
	File_src_lib_types_v1_data_source_proto = out.File
	file_src_lib_types_v1_data_source_proto_goTypes = nil
	file_src_lib_types_v1_data_source_proto_depIdxs = nil
}
